package parser;

import autogenerated.SQLParser.CorrContext;
import org.antlr.v4.runtime.tree.TerminalNodeImpl;
import org.jetbrains.annotations.NotNull;


public class CorrNode extends TerminalNodeImpl {

    private final String text;

    public CorrNode(@NotNull CorrContext context, String corrPattern) {
        // Constructor
        super(context.getStart());

        // The first content
        String col1 = (context.payload(0)).getText();
       
        // The second content
        String col2 = (context.payload(1)).getText();
    
        text = modifyCorr(col1, col2, corrPattern);
    }

    // Returns the modified corr
    private static String modifyCorr(@NotNull String col1, @NotNull String col2, String corrPattern) {
        corrPattern = corrPattern.replace("@column1", col1);
        corrPattern = corrPattern.replace("@column2", col2);

        return corrPattern;
    }


    @Override
    public String getText() {
        return text;
    }

}

