package parser;


import autogenerated.SQLBaseListener;
import autogenerated.SQLParser;

// Implements a listener, which replaces the old token with the new token.
public class CorrListener extends SQLBaseListener {

    // Global parameters
    private final String pattern;

    // Constructor
    public CorrListener(String pattern) {
        this.pattern = pattern;
    }

    @Override
    public void enterCorr(SQLParser.CorrContext ctx) {
       
        // Assembly a new block based on the data
        CorrNode newCorr = new CorrNode(ctx, pattern);
    
        // Remove the old block
        ctx.removeLastChild();
        ctx.removeLastChild();
        ctx.removeLastChild();
        ctx.removeLastChild();
        ctx.removeLastChild();
        ctx.removeLastChild();
    
        // And replace it with the new block
        ctx.addChild(newCorr);
    }
}
