package parser;


import autogenerated.SQLBaseListener;
import autogenerated.SQLParser;
import org.jetbrains.annotations.NotNull;

// Implements a listener, which replaces the old dateDiff token with the new dateDiff token.
public class DateDiffListener extends SQLBaseListener {

    // Global parameters
    private String pattern;

    // Constructor
    public DateDiffListener(String pattern) {
        this.pattern = pattern;
    }

    @Override
    public void enterDatediff(SQLParser.DatediffContext ctx) {
       
        // Assembly a new dateDiff based on the data
        DateDiffNode newNode = new DateDiffNode(ctx, pattern);
    
        // Remove the old dateDiff block
        ctx.removeLastChild();
        ctx.removeLastChild();
        ctx.removeLastChild();
        ctx.removeLastChild();
        ctx.removeLastChild();
        ctx.removeLastChild();
    
        // And replace it with the new dateDiff block
        ctx.addChild(newNode);
    }
}
