package parser;


import autogenerated.SQLBaseListener;
import autogenerated.SQLParser;

// Implements a listener, which replaces the old token with the new token.
public class DateToNumberListener extends SQLBaseListener {

    // Global parameters
    private String pattern;

    // Constructor
    public DateToNumberListener(String pattern) {
        this.pattern = pattern;
    }

    @Override
    public void enterDatetonumber(SQLParser.DatetonumberContext ctx) {
       
        // Assembly a new node (since TerminalNode is not modifiable)
        DateToNumberNode newNode = new DateToNumberNode(ctx, pattern);
    
        // Remove, in total, 4 old nodes:
        ctx.removeLastChild();  // dateToNumber
        ctx.removeLastChild();  // (
        ctx.removeLastChild();  // payload
        ctx.removeLastChild();  // )
    
        // And replace it with the single new node:
        ctx.addChild(newNode);
    }
}
