package parser;

import autogenerated.SQLParser;
import org.antlr.v4.runtime.tree.TerminalNodeImpl;
import org.jetbrains.annotations.NotNull;

public class DateDiffNode extends TerminalNodeImpl {

    private final String text;

    public DateDiffNode(@NotNull SQLParser.DatediffContext context, String pattern) {
        // Constructor
        super(context.getStart());

        // The first content
        String dateTo = (context.payload(0)).getText();

        // The second content
        String dateFrom = (context.payload(1)).getText();

        text = modifyDateDiff(dateTo, dateFrom, pattern);
    }

    // Return the modified dateDiff
    private static String modifyDateDiff(@NotNull String dateTo, @NotNull String dateFrom, String pattern) {
        pattern = pattern.replace("@dateTo", dateTo);
        pattern = pattern.replace("@dateFrom", dateFrom);

        return pattern;
    }

    @Override
    public String getText() {
        return text;
    }
}
