// Generated from /Users/jan/Documents/Git/PredictorFactory/antlr/parser/SQL.g4 by ANTLR 4.5.3
package autogenerated;
import org.antlr.v4.runtime.tree.ParseTreeListener;

/**
 * This interface defines a complete listener for a parse tree produced by
 * {@link SQLParser}.
 */
public interface SQLListener extends ParseTreeListener {
	/**
	 * Enter a parse tree produced by {@link SQLParser#expression}.
	 * @param ctx the parse tree
	 */
	void enterExpression(SQLParser.ExpressionContext ctx);
	/**
	 * Exit a parse tree produced by {@link SQLParser#expression}.
	 * @param ctx the parse tree
	 */
	void exitExpression(SQLParser.ExpressionContext ctx);
	/**
	 * Enter a parse tree produced by {@link SQLParser#bracket}.
	 * @param ctx the parse tree
	 */
	void enterBracket(SQLParser.BracketContext ctx);
	/**
	 * Exit a parse tree produced by {@link SQLParser#bracket}.
	 * @param ctx the parse tree
	 */
	void exitBracket(SQLParser.BracketContext ctx);
	/**
	 * Enter a parse tree produced by {@link SQLParser#datediff}.
	 * @param ctx the parse tree
	 */
	void enterDatediff(SQLParser.DatediffContext ctx);
	/**
	 * Exit a parse tree produced by {@link SQLParser#datediff}.
	 * @param ctx the parse tree
	 */
	void exitDatediff(SQLParser.DatediffContext ctx);
	/**
	 * Enter a parse tree produced by {@link SQLParser#datetonumber}.
	 * @param ctx the parse tree
	 */
	void enterDatetonumber(SQLParser.DatetonumberContext ctx);
	/**
	 * Exit a parse tree produced by {@link SQLParser#datetonumber}.
	 * @param ctx the parse tree
	 */
	void exitDatetonumber(SQLParser.DatetonumberContext ctx);
	/**
	 * Enter a parse tree produced by {@link SQLParser#corr}.
	 * @param ctx the parse tree
	 */
	void enterCorr(SQLParser.CorrContext ctx);
	/**
	 * Exit a parse tree produced by {@link SQLParser#corr}.
	 * @param ctx the parse tree
	 */
	void exitCorr(SQLParser.CorrContext ctx);
	/**
	 * Enter a parse tree produced by {@link SQLParser#from}.
	 * @param ctx the parse tree
	 */
	void enterFrom(SQLParser.FromContext ctx);
	/**
	 * Exit a parse tree produced by {@link SQLParser#from}.
	 * @param ctx the parse tree
	 */
	void exitFrom(SQLParser.FromContext ctx);
	/**
	 * Enter a parse tree produced by {@link SQLParser#table}.
	 * @param ctx the parse tree
	 */
	void enterTable(SQLParser.TableContext ctx);
	/**
	 * Exit a parse tree produced by {@link SQLParser#table}.
	 * @param ctx the parse tree
	 */
	void exitTable(SQLParser.TableContext ctx);
	/**
	 * Enter a parse tree produced by {@link SQLParser#alias}.
	 * @param ctx the parse tree
	 */
	void enterAlias(SQLParser.AliasContext ctx);
	/**
	 * Exit a parse tree produced by {@link SQLParser#alias}.
	 * @param ctx the parse tree
	 */
	void exitAlias(SQLParser.AliasContext ctx);
	/**
	 * Enter a parse tree produced by {@link SQLParser#using}.
	 * @param ctx the parse tree
	 */
	void enterUsing(SQLParser.UsingContext ctx);
	/**
	 * Exit a parse tree produced by {@link SQLParser#using}.
	 * @param ctx the parse tree
	 */
	void exitUsing(SQLParser.UsingContext ctx);
	/**
	 * Enter a parse tree produced by {@link SQLParser#columns}.
	 * @param ctx the parse tree
	 */
	void enterColumns(SQLParser.ColumnsContext ctx);
	/**
	 * Exit a parse tree produced by {@link SQLParser#columns}.
	 * @param ctx the parse tree
	 */
	void exitColumns(SQLParser.ColumnsContext ctx);
	/**
	 * Enter a parse tree produced by {@link SQLParser#on}.
	 * @param ctx the parse tree
	 */
	void enterOn(SQLParser.OnContext ctx);
	/**
	 * Exit a parse tree produced by {@link SQLParser#on}.
	 * @param ctx the parse tree
	 */
	void exitOn(SQLParser.OnContext ctx);
	/**
	 * Enter a parse tree produced by {@link SQLParser#payload}.
	 * @param ctx the parse tree
	 */
	void enterPayload(SQLParser.PayloadContext ctx);
	/**
	 * Exit a parse tree produced by {@link SQLParser#payload}.
	 * @param ctx the parse tree
	 */
	void exitPayload(SQLParser.PayloadContext ctx);
}